#!/bin/bash
set -e

echo "Step1: Test for vault server install"
docker run -t -i sometheycallme/vaultalpha help | grep Usage:

echo "Step2: Initialize Vault and look for key creation"
docker run -t -i sometheycallme/vaultalpha init 
#docker run -t -i sometheycallme/vaultalpha vault server -config=/opt/vault/vaultconfig.hcl | grep Started! 
